#!/usr/bin/perl
# checkpassword
# part of qwik-smtpd MTA server package
# (C) 2002 Amir Malik.
# http://qwikmail.sourceforge.net/smtpd/

my $email = $ARGV[0];

# general regex for validating email address
my $exp = '([^":\s<>()/;]*@[^":\s<>()/;]*)';

# get rid of metacharacters, etc.
$email =~ /$exp/smg;
$email =~ s/(<|>)//g;
$email =~ s/\@virusexperts\.com//ig;

if(-e "/home/$email/") {
  print "success!";
}

exit(0);
