#!/usr/bin/perl
# checkpassword
# part of qwik-smtpd MTA server package
# (C) 2002 Amir Malik.
# http://qwikmail.sourceforge.net/smtpd/

# TODO: add 251 User not local; will forward to <Smith@USC-ISIQ.ARPA>

# general regex for validating email address
my $exp = '([^":\s<>()/;]*@[^":\s<>()/;]*)';

my $email = $ARGV[0];
$email =~ /$exp/smg;
$email =~ s/(<|>|\#|\!|\\|\/|\s)//g;

if(!$email) {
  print "550 configuration error\r\n";
  exit(1);
}

my $dom;
foreach $dom (readMultilineConfig("rcpthosts")) {
  $email =~ s/\@$dom//ig;
}

if(-e "/home/$email/") {
  if(open(FORWARD,"</home/$email/.forward")) {
    my @forwards;
    while(<FORWARD>) {
      chomp;
      next if(length($_) < 2);
      my @addrs = split(/,/, $_);
      foreach my $addr (@addrs) {
        next if(length($addr) < 2);
        push(@forwards, $addr);
      }
    }
    close(FORWARD);
    my $addr = $forwards[0];
    $addr =~ s/\s//g;
    print "551 user not local; please try <$addr>\r\n";
  } else {
    print "250 ok\r\n";
  }
} else {
  print "550 user not here\r\n";
}

exit(0);

sub readMultilineConfig {
  open(CONFIG,"</etc/qwik-smtpd/$_[0]");
  my @conf;
  while(<CONFIG>) {
    chomp;
    next if(length($_) < 2);
    push(@conf,$_);
  }
  close(CONFIG);
  return @conf;
}
